In [20]:
import numpy as np
import os

In [22]:
filepath = 'data/shakespeare.txt'
TOTAL_NUM_POEMS = 154 #this is a one indexed value
NUM_LINES_IN_POEM = 14

last_num_words_in_line = 0
all_num_of_words_per_line = np.zeros((TOTAL_NUM_POEMS, NUM_LINES_IN_POEM))
poem_count = 0
num_lines = 0

with open(filepath) as fp:
    line = fp.readline()
    cnt = 1
    while line:
        print("Line {}: {}".format(cnt, line.strip()))
        number_words_in_line = len(line.split())
        if last_num_words_in_line == 0 and number_words_in_line == 1:
            num_lines = 0
        
        if 1<= num_lines <= 14:
            all_num_of_words_per_line[poem_count, num_lines-1] = number_words_in_line
            
        if num_lines == 15:
            poem_count += 1

        
        print(all_num_of_words_per_line[poem_count, :])
        num_lines += 1    
        cnt += 1
        line = fp.readline()
        last_num_words_in_line = number_words_in_line

Line 1: 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2: From fairest creatures we desire increase,
[6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 3: That thereby beauty's rose might never die,
[6. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 4: But as the riper should by time decease,
[6. 7. 8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 5: His tender heir might bear his memory:
[6. 7. 8. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 6: But thou contracted to thine own bright eyes,
[6. 7. 8. 7. 8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 7: Feed'st thy light's flame with self-substantial fuel,
[6. 7. 8. 7. 8. 7. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 8: Making a famine where abundance lies,
[6. 7. 8. 7. 8. 7. 6. 0. 0. 0. 0. 0. 0. 0.]
Line 9: Thy self thy foe, to thy sweet self too cruel:
[ 6.  7.  8.  7.  8.  7.  6. 10.  0.  0.  0.  0.  0.  0.]
Line 10: Thou that art now the world's fresh ornament,
[ 6.  7.  8.  7.  8.  7.  6. 10.  8.  0.  0.  0.  0.  0.]
Line 11: And only herald to the gaudy spring,
[ 6. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 475: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 476: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 477: 29
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 478: When in disgrace with Fortune and men's eyes,
[8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 479: I all alone beweep my outcast state,
[8. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 480: And trouble deaf heaven with my bootless cries,
[8. 7. 8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 481: And look upon my self and curse my fate,
[8. 7. 8. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 482: Wishing me like to one more rich in hope,
[8. 7. 8. 9. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 483: Featured like him, like him with friends possessed,
[8. 7. 8. 9. 9. 8. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 484: Desiring this man's art, and that man's scope,
[8. 7. 8. 9. 9. 8. 8. 0. 0. 0. 0. 0. 0. 0.]
Line 485: With what I most enjoy contented least,
[8. 7. 8. 9. 9. 8. 8. 7. 0. 0. 0. 0. 0. 0.]
Line

[9. 8. 8. 7. 7. 6. 6. 9. 8. 0. 0. 0. 0. 0.]
Line 1014: And delves the parallels in beauty's brow,
[9. 8. 8. 7. 7. 6. 6. 9. 8. 7. 0. 0. 0. 0.]
Line 1015: Feeds on the rarities of nature's truth,
[9. 8. 8. 7. 7. 6. 6. 9. 8. 7. 7. 0. 0. 0.]
Line 1016: And nothing stands but for his scythe to mow.
[9. 8. 8. 7. 7. 6. 6. 9. 8. 7. 7. 9. 0. 0.]
Line 1017: And yet to times in hope, my verse shall stand
[ 9.  8.  8.  7.  7.  6.  6.  9.  8.  7.  7.  9. 10.  0.]
Line 1018: Praising thy worth, despite his cruel hand.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1019: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1020: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1021: 61
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1022: Is it thy will, thy image should keep open
[9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1023: My heavy eyelids to the weary night?
[9. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1024: Dost thou desire my slumbers should be broken,
[9. 7. 8. 0. 0. 0. 0. 0. 0. 

[8. 8. 9. 5. 8. 7. 7. 7. 0. 0. 0. 0. 0. 0.]
Line 1642: Yet this abundant issue seemed to me
[8. 8. 9. 5. 8. 7. 7. 7. 7. 0. 0. 0. 0. 0.]
Line 1643: But hope of orphans, and unfathered fruit,
[8. 8. 9. 5. 8. 7. 7. 7. 7. 7. 0. 0. 0. 0.]
Line 1644: For summer and his pleasures wait on thee,
[8. 8. 9. 5. 8. 7. 7. 7. 7. 7. 8. 0. 0. 0.]
Line 1645: And thou away, the very birds are mute.
[8. 8. 9. 5. 8. 7. 7. 7. 7. 7. 8. 8. 0. 0.]
Line 1646: Or if they sing, 'tis with so dull a cheer,
[ 8.  8.  9.  5.  8.  7.  7.  7.  7.  7.  8.  8. 10.  0.]
Line 1647: That leaves look pale, dreading the winter's near.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1648: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1649: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1650: 98
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1651: From you have I been absent in the spring,
[9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 1652: When proud-pied April (dressed in all his trim)
[9. 8. 0. 0. 0. 0. 0. 0. 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2260: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2261: 134
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2262: So now I have confessed that he is thine,
[9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2263: And I my self am mortgaged to thy will,
[9. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2264: My self I'll forfeit, so that other mine,
[9. 9. 8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2265: Thou wilt restore to be my comfort still:
[9. 9. 8. 8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Line 2266: But thou wilt not, nor he will not be free,
[ 9.  9.  8.  8. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
Line 2267: For thou art covetous, and he is kind,
[ 9.  9.  8.  8. 10.  8.  0.  0.  0.  0.  0.  0.  0.  0.]
Line 2268: He learned but surety-like to write for me,
[ 9.  9.  8.  8. 10.  8.  8.  0.  0.  0.  0.  0.  0.  0.]
Line 2269: Under that bond that him as fist doth bind.
[ 9.  9.  8.  8. 10.  8.  8.  9.  0.  0.  0.  0.  0.  0.]
Line 227

IndexError: index 154 is out of bounds for axis 0 with size 154